package brand

import (
	"strings"

	"charm.land/lipgloss/v2"
)

// wordmarkArt is the static, embedded terminal-art rendering of WORK. It is a
// design draft (contracts/brand.md, research R12): a hand-placed block-glyph
// asset, deliberately not generated by a runtime figlet dependency. Lines are
// padded to a common width in normalise so every row is a rectangle and the
// per-column gradient in brand.go lines up across all four glyphs.
const wordmarkArt = "" +
	"██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗\n" +
	"██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝\n" +
	"██║ █╗ ██║██║   ██║██████╔╝█████╔╝\n" +
	"██║███╗██║██║   ██║██╔══██╗██╔═██╗\n" +
	"╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗\n" +
	" ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝"

// artLines is wordmarkArt split into rows, each right-padded to artWidth so the
// block is rectangular. artWidth / artHeight are its fixed display dimensions.
var (
	artLines  []string
	artWidth  int
	artHeight int
)

func init() {
	rows := strings.Split(wordmarkArt, "\n")
	for _, r := range rows {
		if w := lipgloss.Width(r); w > artWidth {
			artWidth = w
		}
	}
	artLines = make([]string, len(rows))
	for i, r := range rows {
		if pad := artWidth - lipgloss.Width(r); pad > 0 {
			r += strings.Repeat(" ", pad)
		}
		artLines[i] = r
	}
	artHeight = len(artLines)
}
